# Site settings
title: Phenomenal Machines
email: me àt dônteo dot io
description: > # this means to ignore newlines until "baseurl:"
  "Everything we know is only some kind of approximation, because we
  know that we do not know all the laws as yet. Therefore, things must
  be learned only to be unlearned again or, more likely, to be
  corrected." --R. Feynman
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neutralino.github.io" # the base hostname & protocol for your site
twitter_username: neutralinoz
github_username:  neutralino

# Build settings
markdown: kramdown
